### ISSUE TITLE
Direct link in `README` to the schema files

### ISSUE THREAD

**Issue by romaintailhurat** [InseeFr/Lunatic-Model#114]
From my point of view, the main products of this repo are the two schemas, [LunaticModel](https://github.com/InseeFr/Lunatic-Model/blob/master/src/main/resources/xsd/LunaticModel.xsd) and [LunaticModelFlat](https://github.com/InseeFr/Lunatic-Model/blob/master/src/main/resources/xsd/LunaticModelFlat.xsd).

I would ❤️ a direct link to those in the `README.md`.

**Comment by nsenave** [comment]
Since v3 of Lunatic-Model lib, the hierarchical model has been abandoned, and xml schemas have been removed.

From now on, the model is described by the Java classes.

Lunatic-Model is a java lib that allow serialization/deserialization of Lunatic json questionnaires. This project does not define the Lunatic model (although its name suggests it): [Lunatic](https://github.com/InseeFr/Lunatic) does (changes in the questionnaire model in Lunatic are brought in Lunatic-Model in a second stage).

Yet, if needed, we might implement the generation of a Json Schema from java classes for instance.

For the `README.md`, I'll update it with the pieces of information I've given here 😄 + maybe add links to Lunatic typescript files that define the model.

**Comment by nsenave** [comment]
652b77081338c671a073e4e1ba8dd25071947d58
