### ISSUE TITLE
Problem with logs (log4j / log4j2.xml config file)

### ISSUE THREAD

**Issue by aude-mulliez** [InseeFr/Lunatic-Model#20]
We use Lunatic-model as dependency in our project (prisme) and we have an issue with logging system. 

You have a log4j2.xml config file in your lunatic-model.jar, and it writes in a lunatic.log rollingfile...  Your log4j2.xml is used in place of our own log4j2.xml file (surely because "Lunatic" is before "Prisme" in the alphabetical order) resulting in our logs writing into a lunatic file...

Could you please delete the log4J dependency and the config file (let slf4j only and we do the  job when using your library).

Tks !

**Comment by olevitt** [comment]
I suggest the following changes :  
* Remove log4j2 dependency and log4j2.xml (as suggested)  
* Add log4j2 dependency as scope `test` so that we continue to get logs during tests 
* Make sure we have no usages of log4j2 within src/main/java code (I made a first pass and didn't find any as the code is already using slf4j)  

I will submit a PR with this changes
